using Compunet.SudokuSolver.Core;
using System.Windows;
using System.Windows.Controls;

namespace Compunet.SudokuSolver.Print
{
    public class PrintService : IPrintService
    {
        public void PrintBoard(IBoard board)
        {
            PrintDialog dialog = new();

            if (dialog.ShowDialog() == true)
            {
                var stack = new StackPanel()
                {
                    VerticalAlignment = VerticalAlignment.Top,
                    HorizontalAlignment = HorizontalAlignment.Center,
                    Margin = new Thickness(50),
                };

                stack.Children.Add(new SudokuVisual(board));

                stack.Children.Add(new TextBlock()
                {
                    Text = "generated by - compunet.sudoku-solver",
                    FontSize = 10,
                    Margin = new Thickness(0, 10, 0, 0)
                });

                dialog.PrintVisual(stack, "Compunet.Sudoku");
            }
        }
    }
}
